
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

public class bahanbaku extends javax.swing.JPanel {

    private DefaultTableModel tabModel;
    private Connection conn;
    private PreparedStatement pst;
    private ResultSet rs;

    private void tampil_barang() {

        Object[] baris = {"Kode Bahan", "Nama Bahan", "Jumlah Stok", "Satuan", "Harga PerSatuan", "Status Stok"};
        tabModel = new DefaultTableModel(null, baris);
        tbl_bahanbaku.setModel(tabModel);
        String sql = "select * from bahan_baku order by kd_bahan asc";
        try {
            Connection konek = new Config().ConfigDB();
            Statement stat = konek.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String kode_bahan = hasil.getString("kd_bahan");
                String nama_bahan = hasil.getString("nama_bahan");
                String Stok = hasil.getString("jumlah_stok");
                String Satuan = hasil.getString("satuan");
                String Harga = hasil.getString("harga_bahan");
                String Status = hasil.getString("status_stok");
                String[] data = {kode_bahan, nama_bahan, Stok, Satuan, Harga, Status};
                tabModel.addRow(data);

            }
            konek.close();
        } catch (Exception e) {

        }
    }

    public bahanbaku() {
        initComponents();
        tampil_barang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        text_cari = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_bahanbaku = new Assets.CTable();

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setPreferredSize(new java.awt.Dimension(1024, 753));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("STOK BAHAN BAKU");

        text_cari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                text_cariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                text_cariFocusLost(evt);
            }
        });
        text_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                text_cariMouseEntered(evt);
            }
        });
        text_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_cariActionPerformed(evt);
            }
        });
        text_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_cariKeyTyped(evt);
            }
        });

        btn_cari.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_cari.setText("CARI");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 0, 0));
        jButton4.setText("Tambah");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tbl_bahanbaku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(tbl_bahanbaku);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton4))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btn_cari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                                .addComponent(text_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 753, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void text_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_cariActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        String kataCari = text_cari.getText().trim();

        // Validasi jika TextField kosong
        if (kataCari.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silakan masukkan kata kunci pencarian!");
            text_cari.requestFocus();
            return;
        }

        try {
            // Mengosongkan tabel
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();

            // Query pencarian
            String sql = "SELECT * FROM bahan_baku WHERE nama_bahan LIKE ?";
            Connection konek = new Config().ConfigDB();
            pst = konek.prepareStatement(sql);
            pst.setString(1, "%" + kataCari + "%");
            rs = pst.executeQuery();

            boolean ditemukan = false;

            // Menampilkan hasil pencarian ke tabel
            while (rs.next()) {
                ditemukan = true;
                Object[] obj = new Object[6];
                obj[0] = rs.getString("kd_bahan");
                obj[1] = rs.getString("nama_bahan");
                obj[2] = rs.getString("jumlah_stok");
                obj[3] = rs.getString("satuan");
                obj[4] = rs.getString("harga_bahan");
                obj[5] = rs.getString("status_stok");
                //obj[4] = "Rp " + String.format("%,d", rs.getInt("harga"));

                tabModel.addRow(obj);
            }

            // Jika data tidak ditemukan
            if (!ditemukan) {
                JOptionPane.showMessageDialog(this,
                        "Data bahan baku dengan kata kunci '" + kataCari + "' tidak ditemukan!");
                text_cari.setText("");
                text_cari.requestFocus();
                //tampil_barang(); // Menampilkan kembali semua data
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error pencarian: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_cariActionPerformed


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void text_cariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_cariFocusLost
        // TODO add your handling code here:


    }//GEN-LAST:event_text_cariFocusLost

    private void text_cariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_cariFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_text_cariFocusGained

    private void text_cariMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_cariMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_text_cariMouseEntered

    private void text_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_cariKeyTyped
        // TODO add your handling code here:
        if (text_cari.getText().trim().isEmpty()) {
            tampil_barang();  // Panggil metode untuk menampilkan semua data
            System.out.println("berhasil");
        } 
    }//GEN-LAST:event_text_cariKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private Assets.CTable tbl_bahanbaku;
    private javax.swing.JTextField text_cari;
    // End of variables declaration//GEN-END:variables
}
