/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author acer
 */
public class FormKiriMenu extends javax.swing.JPanel {

    /**
     * Creates new form FormKiriMenu
     */
    public FormKiriMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_kiri = new javax.swing.JPanel();
        btn_laporan = new javax.swing.JButton();
        btn_pembayaran = new javax.swing.JButton();
        btn_user = new javax.swing.JButton();
        btn_bahan = new javax.swing.JButton();
        btn_menu = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.CardLayout());
        add(jPanel1, "card2");

        panel_kiri.setBackground(new java.awt.Color(102, 0, 0));
        panel_kiri.setPreferredSize(new java.awt.Dimension(350, 753));

        btn_laporan.setBackground(new java.awt.Color(102, 0, 0));
        btn_laporan.setFont(new java.awt.Font("Sora", 1, 20)); // NOI18N
        btn_laporan.setForeground(new java.awt.Color(255, 255, 255));
        btn_laporan.setText("Laporan Penghasilan");
        btn_laporan.setBorderPainted(false);
        btn_laporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanActionPerformed(evt);
            }
        });

        btn_pembayaran.setBackground(new java.awt.Color(102, 0, 0));
        btn_pembayaran.setFont(new java.awt.Font("Sora", 1, 24)); // NOI18N
        btn_pembayaran.setForeground(new java.awt.Color(255, 255, 255));
        btn_pembayaran.setText("Pembayaran");
        btn_pembayaran.setBorderPainted(false);
        btn_pembayaran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btn_user.setBackground(new java.awt.Color(102, 0, 0));
        btn_user.setFont(new java.awt.Font("Sora", 1, 24)); // NOI18N
        btn_user.setForeground(new java.awt.Color(255, 255, 255));
        btn_user.setText("User");
        btn_user.setBorderPainted(false);
        btn_user.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btn_bahan.setBackground(new java.awt.Color(102, 0, 0));
        btn_bahan.setFont(new java.awt.Font("Sora", 1, 24)); // NOI18N
        btn_bahan.setForeground(new java.awt.Color(255, 255, 255));
        btn_bahan.setText("Bahan Baku");
        btn_bahan.setBorderPainted(false);
        btn_bahan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_bahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bahanActionPerformed(evt);
            }
        });

        btn_menu.setFont(new java.awt.Font("Sora", 1, 24)); // NOI18N
        btn_menu.setForeground(new java.awt.Color(102, 0, 0));
        btn_menu.setText("Menu");
        btn_menu.setBorderPainted(false);
        btn_menu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_kiriLayout = new javax.swing.GroupLayout(panel_kiri);
        panel_kiri.setLayout(panel_kiriLayout);
        panel_kiriLayout.setHorizontalGroup(
            panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kiriLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_kiriLayout.createSequentialGroup()
                        .addGroup(panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_bahan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panel_kiriLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63))
                    .addGroup(panel_kiriLayout.createSequentialGroup()
                        .addGroup(panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_pembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(btn_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(38, Short.MAX_VALUE))))
        );
        panel_kiriLayout.setVerticalGroup(
            panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_kiriLayout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addComponent(btn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_bahan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_user, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
        );

        add(panel_kiri, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_laporanActionPerformed

    private void btn_bahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bahanActionPerformed
        MenuBahanBaku m_bahanbaku = new MenuBahanBaku();

        // Atur posisi form baru (opsional, agar muncul di posisi yang sama)
        m_bahanbaku.setLocation(this.getLocation());

        // Tampilkan form baru dulu
        m_bahanbaku.setVisible(true);

        // Baru sembunyikan form saat ini
        this.setVisible(false);
    }//GEN-LAST:event_btn_bahanActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_menuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bahan;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_pembayaran;
    private javax.swing.JButton btn_user;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_kiri;
    // End of variables declaration//GEN-END:variables
}
