/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class LogIn extends javax.swing.JPanel {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_posisi = new javax.swing.JComboBox<>();
        panel_utama = new javax.swing.JPanel();
        panel_login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text_password = new javax.swing.JTextField();
        posisi = new javax.swing.JComboBox<>();
        btn_daftar1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        text_posisi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        text_posisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Posisi", "Admin", "Kasir" }));
        text_posisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_posisiActionPerformed(evt);
            }
        });

        setPreferredSize(new java.awt.Dimension(440, 330));
        setLayout(new java.awt.CardLayout());

        panel_utama.setOpaque(false);
        panel_utama.setPreferredSize(new java.awt.Dimension(440, 330));
        panel_utama.setLayout(new java.awt.CardLayout());

        panel_login.setPreferredSize(new java.awt.Dimension(1024, 753));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel1.setText("LOGIN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("NAMA :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("PASSWORD :");

        posisi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        posisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Posisi", "Admin", "Kasir" }));
        posisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posisiActionPerformed(evt);
            }
        });

        btn_daftar1.setBackground(new java.awt.Color(102, 0, 0));
        btn_daftar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_daftar1.setForeground(new java.awt.Color(255, 255, 255));
        btn_daftar1.setText("LogIn");
        btn_daftar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_daftar1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setText("Anda belum mendaftar akun?");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("Daftar");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login);
        panel_login.setLayout(panel_loginLayout);
        panel_loginLayout.setHorizontalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(178, 178, 178))
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(text_nama, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(text_password)))
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(posisi, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_loginLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btn_daftar1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panel_loginLayout.setVerticalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_password, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(posisi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_daftar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        panel_utama.add(panel_login, "card2");

        add(panel_utama, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void text_posisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_posisiActionPerformed

        // Untuk mengatur item yang terpilih berdasarkan index
        //text_posisi.setSelectedIndex(0); // Memilih item ke-3 (index dimulai dari 0)
        // Untuk mendapatkan index yang terpilih

    }//GEN-LAST:event_text_posisiActionPerformed

    private void btn_daftar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_daftar1ActionPerformed
        try {
            String sql = "SELECT * FROM user WHERE nama ='" + text_nama.getText()
                    + "'AND password ='" + text_password.getText() + "'";
            java.sql.Connection con = (Connection) Config.ConfigDB();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            String selectedRole = (String) posisi.getSelectedItem();
            if (rs.next()) {
                if (text_nama.getText().equals(rs.getString("nama"))
                        && text_password.getText().equals(rs.getString("password"))) {
                    if (selectedRole.equals("Pilih Posisi")) {
                        text_nama.setText("");
                        text_password.setText("");
                        PopWarningPosisi popposisi = new PopWarningPosisi();
                        popposisi.setVisible(true);
                        popposisi.setAnimationSpeed(5);
                        popposisi.showSlideUp();
                    } else {
                        this.setVisible(false);
                        this.removeAll();
                        new FormLogin().setVisible(false);
                        new Menu().setVisible(true);
                    }
                    //JOptionPane.showMessageDialog(null, "berhasil login");

                }
            } else {
                JOptionPane.showMessageDialog(null, "nama atau password salah");
                if (selectedRole.equals("Pilih Posisi")) {

                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btn_daftar1ActionPerformed

    private void posisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posisiActionPerformed
        // Untuk mengatur item yang terpilih berdasarkan index
        //text_posisi.setSelectedIndex(0); // Memilih item ke-3 (index dimulai dari 0)
        // Untuk mendapatkan index yang terpilih
    }//GEN-LAST:event_posisiActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        panel_utama.removeAll();
        panel_utama.add(new Daftar());
        panel_utama.repaint();
        panel_utama.revalidate();
    }//GEN-LAST:event_jLabel6MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_daftar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panel_login;
    private javax.swing.JPanel panel_utama;
    private javax.swing.JComboBox<String> posisi;
    private javax.swing.JTextField text_nama;
    private javax.swing.JTextField text_password;
    private javax.swing.JComboBox<String> text_posisi;
    // End of variables declaration//GEN-END:variables
}
