/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;

/**
 *
 * @author acer
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_kiri = new javax.swing.JPanel();
        btn_menu = new javax.swing.JButton();
        btn_bahan = new javax.swing.JButton();
        btn_user = new javax.swing.JButton();
        btn_pembayaran = new javax.swing.JButton();
        btn_laporan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panel_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panel_kiri.setBackground(new java.awt.Color(102, 0, 0));

        btn_menu.setFont(new java.awt.Font("Sora", 1, 24)); // NOI18N
        btn_menu.setForeground(new java.awt.Color(102, 0, 0));
        btn_menu.setText("Menu");
        btn_menu.setBorderPainted(false);
        btn_menu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        btn_bahan.setBackground(new java.awt.Color(102, 0, 0));
        btn_bahan.setFont(new java.awt.Font("Sora", 1, 24)); // NOI18N
        btn_bahan.setForeground(new java.awt.Color(255, 255, 255));
        btn_bahan.setText("Bahan Baku");
        btn_bahan.setBorderPainted(false);
        btn_bahan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_bahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bahanActionPerformed(evt);
            }
        });

        btn_user.setBackground(new java.awt.Color(102, 0, 0));
        btn_user.setFont(new java.awt.Font("Sora", 1, 24)); // NOI18N
        btn_user.setForeground(new java.awt.Color(255, 255, 255));
        btn_user.setText("User");
        btn_user.setBorderPainted(false);
        btn_user.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userActionPerformed(evt);
            }
        });

        btn_pembayaran.setBackground(new java.awt.Color(102, 0, 0));
        btn_pembayaran.setFont(new java.awt.Font("Sora", 1, 24)); // NOI18N
        btn_pembayaran.setForeground(new java.awt.Color(255, 255, 255));
        btn_pembayaran.setText("Pembayaran");
        btn_pembayaran.setBorderPainted(false);
        btn_pembayaran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pembayaranActionPerformed(evt);
            }
        });

        btn_laporan.setBackground(new java.awt.Color(102, 0, 0));
        btn_laporan.setFont(new java.awt.Font("Sora", 1, 20)); // NOI18N
        btn_laporan.setForeground(new java.awt.Color(255, 255, 255));
        btn_laporan.setText("Laporan Penghasilan");
        btn_laporan.setBorderPainted(false);
        btn_laporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo warung djoglo sri terbaru PUTIH.png"))); // NOI18N

        javax.swing.GroupLayout panel_kiriLayout = new javax.swing.GroupLayout(panel_kiri);
        panel_kiri.setLayout(panel_kiriLayout);
        panel_kiriLayout.setHorizontalGroup(
            panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_bahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_pembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_laporan, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addGroup(panel_kiriLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_kiriLayout.setVerticalGroup(
            panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_kiriLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_bahan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_user, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );

        panel_utama.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                panel_utamaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        panel_utama.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                panel_utamaComponentMoved(evt);
            }
        });
        panel_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_kiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_utama, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_kiri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        panel_utama.add(new Makanan());
        panel_utama.repaint();
        panel_utama.revalidate();
    }//GEN-LAST:event_formWindowActivated

    private void panel_utamaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_panel_utamaAncestorAdded

    }//GEN-LAST:event_panel_utamaAncestorAdded

    private void panel_utamaComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panel_utamaComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_utamaComponentMoved

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        // TODO add your handling code here:
        btn_bahan.setBackground(new Color(102, 0, 0));
        btn_bahan.setForeground(new Color(255, 255, 255));
        btn_user.setBackground(new Color(102, 0, 0));
        btn_user.setForeground(new Color(255, 255, 255));
        btn_pembayaran.setBackground(new Color(102, 0, 0));
        btn_pembayaran.setForeground(new Color(255, 255, 255));
        btn_laporan.setBackground(new Color(102, 0, 0));
        btn_laporan.setForeground(new Color(255, 255, 255));

        btn_menu.setBackground(new Color(255, 255, 255));
        btn_menu.setForeground(new Color(102, 0, 0));

        panel_utama.removeAll();
        panel_utama.add(new Makanan());
        panel_utama.repaint();
        panel_utama.revalidate();
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_bahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bahanActionPerformed
        btn_menu.setBackground(new Color(102, 0, 0));
        btn_menu.setForeground(new Color(255, 255, 255));
        btn_user.setBackground(new Color(102, 0, 0));
        btn_user.setForeground(new Color(255, 255, 255));
        btn_pembayaran.setBackground(new Color(102, 0, 0));
        btn_pembayaran.setForeground(new Color(255, 255, 255));
        btn_laporan.setBackground(new Color(102, 0, 0));
        btn_laporan.setForeground(new Color(255, 255, 255));

        btn_bahan.setBackground(new Color(255, 255, 255));
        btn_bahan.setForeground(new Color(102, 0, 0));

        panel_utama.removeAll();
        panel_utama.add(new bahanbaku());
        panel_utama.repaint();
        panel_utama.revalidate();

    }//GEN-LAST:event_btn_bahanActionPerformed

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        // TODO add your handling code here:
        btn_bahan.setBackground(new Color(102, 0, 0));
        btn_bahan.setForeground(new Color(255, 255, 255));
        btn_menu.setBackground(new Color(102, 0, 0));
        btn_menu.setForeground(new Color(255, 255, 255));
        btn_user.setBackground(new Color(102, 0, 0));
        btn_user.setForeground(new Color(255, 255, 255));
        btn_pembayaran.setBackground(new Color(102, 0, 0));
        btn_pembayaran.setForeground(new Color(255, 255, 255));

        btn_laporan.setBackground(new Color(255, 255, 255));
        btn_laporan.setForeground(new Color(102, 0, 0));
    }//GEN-LAST:event_btn_laporanActionPerformed

    private void btn_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userActionPerformed
        // TODO add your handling code here:
        btn_bahan.setBackground(new Color(102, 0, 0));
        btn_bahan.setForeground(new Color(255, 255, 255));
        btn_menu.setBackground(new Color(102, 0, 0));
        btn_menu.setForeground(new Color(255, 255, 255));
        btn_pembayaran.setBackground(new Color(102, 0, 0));
        btn_pembayaran.setForeground(new Color(255, 255, 255));
        btn_laporan.setBackground(new Color(102, 0, 0));
        btn_laporan.setForeground(new Color(255, 255, 255));

        btn_user.setBackground(new Color(255, 255, 255));
        btn_user.setForeground(new Color(102, 0, 0));
    }//GEN-LAST:event_btn_userActionPerformed

    private void btn_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pembayaranActionPerformed
        // TODO add your handling code here:
        btn_bahan.setBackground(new Color(102, 0, 0));
        btn_bahan.setForeground(new Color(255, 255, 255));
        btn_menu.setBackground(new Color(102, 0, 0));
        btn_menu.setForeground(new Color(255, 255, 255));
        btn_user.setBackground(new Color(102, 0, 0));
        btn_user.setForeground(new Color(255, 255, 255));
        btn_laporan.setBackground(new Color(102, 0, 0));
        btn_laporan.setForeground(new Color(255, 255, 255));

        btn_pembayaran.setBackground(new Color(255, 255, 255));
        btn_pembayaran.setForeground(new Color(102, 0, 0));
    }//GEN-LAST:event_btn_pembayaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bahan;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_pembayaran;
    private javax.swing.JButton btn_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel_kiri;
    private javax.swing.JPanel panel_utama;
    // End of variables declaration//GEN-END:variables
}
